name = "stonk-rider"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-13"
[[d1_databases]]
binding = "DB"
database_name = "stonk-rider-db"
database_id = "c080c589-10ce-4401-b1e9-00e6776223c0"
